/*
 * K8ssandra Cluster API
 *
 * A RESTful service providing control and visibility into a K8ssandra cluster.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type CassandraDatacenter struct {

	ApiVersion string `json:"apiVersion,omitempty"`

	Kind string `json:"kind,omitempty"`

	Metadata *ResourceMetadata `json:"metadata,omitempty"`

	Status *CassandraDatacenterStatus `json:"status,omitempty"`

	Spec *CassandraDatacenterSpec `json:"spec,omitempty"`
}
