/*
 * K8ssandra Cluster API
 *
 * A RESTful service providing control and visibility into a K8ssandra cluster.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type WrapperMetadata struct {

	Total int32 `json:"total,omitempty"`

	Count int32 `json:"count,omitempty"`
}
